name: "CI: Build Containers"

on:
  push:
    branches: [$default-branch]

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build .NET App
        uses: brocksolutions/action-build-container@v3
        with:
          image-name: your-image-name
          dockerfile-path: your-dockerfile-path/Dockerfile
