name: CI workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build .NET App
        uses: brocksolutions-pe/action-build-test-dotnet@main
        with:
          solution-file: your-solution-file.sln
