name: "CI: Build and Test .NET Solution"

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build .NET App
        uses: brocksolutions/action-build-test-dotnet@v2
        with:
          solution-file: your-solution-file.sln
