name: Deploy Infrastructure
on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest-deployment
    environment: streams-platform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_STREAMS }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_STREAMS }}

      - name: Pull secrets
        id: pull-secrets
        uses: brocksolutions/action-pull-secrets@v1
        with:
          key-vault-name: ${{ secrets.AZURE_KEY_VAULT_NAME_STREAMS }}
          tf-api-token-secret-name: ${{ secrets.TF_API_TOKEN_SECRET_NAME }}
          github-pat-secret-name: ${{ secrets.GH_PAT_SECRET_NAME }}
          app-config-kv-secret-name: ${{ secrets.AZURE_APP_CONFIG_KV_SECRET_NAME }}

      - name: Terraform Plan
        uses: brocksolutions/action-plan-terraform@v1
        with:
          tf-api-token: ${{ steps.pull-secrets.outputs.tf-api-token }}
          github-pat: ${{ steps.pull-secrets.outputs.gh-pat }}
          tf-var-file: your-variable-file-path.tfvars
        env:
          TF_VAR_registry_secret_name: ${{ secrets.GH_PAT_SECRET_NAME }}
          TF_VAR_platform_key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME_STREAMS }}
          TF_VAR_app_config_key_vault_name: ${{ steps.pull-secrets.outputs.app-config-kv-name }}

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest-deployment
    environment: streams-platform
    needs: plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_STREAMS }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_STREAMS }}

      - name: Pull secrets
        id: pull-secrets
        uses: brocksolutions/action-pull-secrets@v1
        with:
          key-vault-name: ${{ secrets.AZURE_KEY_VAULT_NAME_STREAMS }}
          tf-api-token-secret-name: ${{ secrets.TF_API_TOKEN_SECRET_NAME }}
          github-pat-secret-name: ${{ secrets.GH_PAT_SECRET_NAME }}
          app-config-kv-secret-name: ${{ secrets.AZURE_APP_CONFIG_KV_SECRET_NAME }}

      - name: Terraform Apply
        uses: brocksolutions/action-apply-terraform@v1
        with:
          tf-api-token: ${{ steps.pull-secrets.outputs.tf-api-token }}
          github-pat: ${{ steps.pull-secrets.outputs.gh-pat }}
          tf-var-file: your-variable-file-path.tfvars
        env:
          TF_VAR_registry_secret_name: ${{ secrets.GH_PAT_SECRET_NAME }}
          TF_VAR_platform_key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME_STREAMS }}
          TF_VAR_app_config_key_vault_name: ${{ steps.pull-secrets.outputs.app-config-kv-name }}
