name: Terraform Scan and Test
on:
  push:
    branches: [ $default-branch ]

permissions:
  id-token: write
  contents: read

jobs:
  scan-and-test:
    name: Scan and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: brocksolutions/action-scan-terraform@v1

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.TERRAFORM_RELEASE_CREDS }}
          allow-no-subscriptions: true

      - uses: brocksolutions/action-test-terraform@v1
        with:
          github-pat: ${{ secrets.GH_PAT }}
